import { BrowserRouter, Routes, Route } from "react-router-dom";
import { useState } from "react";

import Dashboard from "./Pages/Dashboard";
import Employees from "./Pages/Employees";
import NotFound from "./Pages/NotFound";

import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";

export default function App() {
  const [employees, setEmployees] = useState([
    {
      id: 1,
      name: "Rahul Sharma",
      role: "React Developer",
      department: "Development",
      joined: "2024-12-10",
      leave: false,
      salary: 55000,
      email: "rahul.sharma@example.com",
      phone: "9876543210",
      location: "Hyderabad",
    },
    {
      id: 2,
      name: "Priya Singh",
      role: "QA Engineer",
      department: "QA",
      joined: "2025-01-05",
      leave: true,
      salary: 45000,
      email: "priya.singh@example.com",
      phone: "9823456712",
      location: "Bangalore",
    },
    {
      id: 3,
      name: "Anil Kumar",
      role: "HR Manager",
      department: "HR",
      joined: "2024-11-15",
      leave: false,
      salary: 60000,
      email: "anil.kumar@example.com",
      phone: "9871234560",
      location: "Hyderabad",
    },
    {
      id: 4,
      name: "Sravani Reddy",
      role: "UI/UX Designer",
      department: "Design",
      joined: "2025-02-18",
      leave: false,
      salary: 52000,
      email: "sravani.reddy@example.com",
      phone: "9908765431",
      location: "Chennai",
    },
    {
      id: 5,
      name: "Kiran Varma",
      role: "Backend Developer",
      department: "Development",
      joined: "2025-03-01",
      leave: false,
      salary: 57000,
      email: "kiran.varma@example.com",
      phone: "9812345670",
      location: "Bangalore",
    },
    {
      id: 6,
      name: "Harika Devi",
      role: "Data Analyst",
      department: "Analytics",
      joined: "2025-03-18",
      leave: false,
      salary: 50000,
      email: "harika.devi@example.com",
      phone: "9898123450",
      location: "Hyderabad",
    },
    {
      id: 7,
      name: "Mohit Verma",
      role: "Support Engineer",
      department: "Support",
      joined: "2025-02-10",
      leave: true,
      salary: 38000,
      email: "mohit.verma@example.com",
      phone: "9786543210",
      location: "Delhi",
    },
    {
      id: 8,
      name: "Deepak Sahu",
      role: "Node.js Developer",
      department: "Development",
      joined: "2025-04-01",
      leave: false,
      salary: 56000,
      email: "deepak.sahu@example.com",
      phone: "9123456780",
      location: "Mumbai",
    },
    {
      id: 9,
      name: "Lakshmi Narayana",
      role: "Cloud Engineer",
      department: "Infrastructure",
      joined: "2024-10-28",
      leave: false,
      salary: 62000,
      email: "lakshmi.n@example.com",
      phone: "9998887776",
      location: "Hyderabad",
    },
    {
      id: 10,
      name: "Sneha Chowdary",
      role: "Intern",
      department: "Development",
      joined: "2025-05-01",
      leave: false,
      salary: 15000,
      email: "sneha.chowdary@example.com",
      phone: "9988776655",
      location: "Vijayawada",
    },

    // --- EMPLOYEES 11 to 30 ---
    {
      id: 11,
      name: "Vikram Desai",
      role: "Project Manager",
      department: "Management",
      joined: "2024-09-20",
      leave: false,
      salary: 80000,
      email: "vikram.desai@example.com",
      phone: "9876001234",
      location: "Hyderabad",
    },
    {
      id: 12,
      name: "Rohit Patil",
      role: "DevOps Engineer",
      department: "Infrastructure",
      joined: "2025-01-28",
      leave: false,
      salary: 65000,
      email: "rohit.patil@example.com",
      phone: "9867543210",
      location: "Pune",
    },
    {
      id: 13,
      name: "Bhavana Sree",
      role: "Frontend Developer",
      department: "Development",
      joined: "2025-01-12",
      leave: false,
      salary: 54000,
      email: "bhavana.sree@example.com",
      phone: "9912345678",
      location: "Hyderabad",
    },
    {
      id: 14,
      name: "Abhinav Kulkarni",
      role: "Database Admin",
      department: "Infrastructure",
      joined: "2024-12-22",
      leave: false,
      salary: 60000,
      email: "abhinav.k@example.com",
      phone: "9877123456",
      location: "Mumbai",
    },
    {
      id: 15,
      name: "Shilpa Raj",
      role: "HR Executive",
      department: "HR",
      joined: "2025-03-02",
      leave: false,
      salary: 40000,
      email: "shilpa.raj@example.com",
      phone: "8877665544",
      location: "Chennai",
    },
    {
      id: 16,
      name: "Jayanth Reddy",
      role: "System Admin",
      department: "Support",
      joined: "2024-11-30",
      leave: false,
      salary: 45000,
      email: "jayanth.reddy@example.com",
      phone: "9988443322",
      location: "Hyderabad",
    },
    {
      id: 17,
      name: "Tejaswini Rao",
      role: "Business Analyst",
      department: "Analytics",
      joined: "2025-02-01",
      leave: false,
      salary: 52000,
      email: "tejaswini.rao@example.com",
      phone: "9876778899",
      location: "Bangalore",
    },
    {
      id: 18,
      name: "Rajesh Kumar",
      role: "UI Developer",
      department: "Design",
      joined: "2024-10-15",
      leave: false,
      salary: 49000,
      email: "rajesh.k@example.com",
      phone: "9765432109",
      location: "Chennai",
    },
    {
      id: 19,
      name: "Swetha Varshini",
      role: "Angular Developer",
      department: "Development",
      joined: "2025-04-12",
      leave: false,
      salary: 58000,
      email: "swetha.v@example.com",
      phone: "9876541122",
      location: "Hyderabad",
    },
    {
      id: 20,
      name: "Ramesh Goud",
      role: "Support Executive",
      department: "Support",
      joined: "2025-03-15",
      leave: false,
      salary: 35000,
      email: "ramesh.g@example.com",
      phone: "8899776655",
      location: "Delhi",
    },
    {
      id: 21,
      name: "Mahesh Babu",
      role: "Java Developer",
      department: "Development",
      joined: "2025-03-10",
      leave: false,
      salary: 58000,
      email: "mahesh.b@example.com",
      phone: "9877001122",
      location: "Hyderabad",
    },
    {
      id: 22,
      name: "Sunitha Devi",
      role: "Content Writer",
      department: "Marketing",
      joined: "2024-12-05",
      leave: false,
      salary: 30000,
      email: "sunitha.d@example.com",
      phone: "9876654321",
      location: "Hyderabad",
    },
    {
      id: 23,
      name: "Chandu Kumar",
      role: "Marketing Manager",
      department: "Marketing",
      joined: "2025-01-20",
      leave: false,
      salary: 55000,
      email: "chandu.k@example.com",
      phone: "9888123444",
      location: "Bangalore",
    },
    {
      id: 24,
      name: "Niharika Reddy",
      role: "Data Engineer",
      department: "Analytics",
      joined: "2025-02-15",
      leave: false,
      salary: 63000,
      email: "niharika.r@example.com",
      phone: "9876655544",
      location: "Hyderabad",
    },
    {
      id: 25,
      name: "Sharath Chandra",
      role: "Full Stack Developer",
      department: "Development",
      joined: "2025-04-22",
      leave: false,
      salary: 65000,
      email: "sharath.c@example.com",
      phone: "9876549088",
      location: "Chennai",
    },
    {
      id: 26,
      name: "Geetha Lakshmi",
      role: "Finance Analyst",
      department: "Finance",
      joined: "2024-09-15",
      leave: false,
      salary: 48000,
      email: "geetha.l@example.com",
      phone: "9867443322",
      location: "Hyderabad",
    },
    {
      id: 27,
      name: "Bharath Kumar",
      role: "Test Engineer",
      department: "QA",
      joined: "2025-03-12",
      leave: false,
      salary: 42000,
      email: "bharath.k@example.com",
      phone: "9877554433",
      location: "Chennai",
    },
    {
      id: 28,
      name: "Keerthi Sree",
      role: "Junior Developer",
      department: "Development",
      joined: "2025-05-05",
      leave: false,
      salary: 38000,
      email: "keerthi.s@example.com",
      phone: "9988771100",
      location: "Hyderabad",
    },
    {
      id: 29,
      name: "Suresh Yadav",
      role: "Network Engineer",
      department: "Infrastructure",
      joined: "2024-11-10",
      leave: false,
      salary: 55000,
      email: "suresh.y@example.com",
      phone: "8899445566",
      location: "Delhi",
    },
    {
      id: 30,
      name: "Pooja Sharma",
      role: "SEO Specialist",
      department: "Marketing",
      joined: "2025-03-01",
      leave: false,
      salary: 32000,
      email: "pooja.s@example.com",
      phone: "9876677889",
      location: "Hyderabad",
    },
  ]);

  return (
    <BrowserRouter>
      <div className="app-container">
        <Sidebar />

        <div className="main-content">
          <Navbar />

          <Routes>
            <Route path="/" element={<Dashboard employees={employees} />} />

            <Route
              path="/employees"
              element={
                <Employees employees={employees} setEmployees={setEmployees} />
              }
            />

            <Route path="*" element={<NotFound />} />
          </Routes>
        </div>
      </div>
    </BrowserRouter>
  );
}
